### ISSUE TITLE
PyTorch data precessing

### ISSUE THREAD

**Issue by Lucca-cherries** [rail-berkeley/bridge_data_v2#6]
Thanks for your wonderful work! We are very interested in utilizing this excellent dataset. By the way, since we are more familiar with PyTorch, do you have a PyTorch version of processing the data?

**Comment by vyeevani** [comment]
I wrote this for the scripted PyTorch dataset: https://gist.github.com/vyeevani/a52a03f5c960d409f9107b8ac8ec709f

**Comment by Lucca-cherries** [comment]
> I wrote this for the scripted PyTorch dataset: https://gist.github.com/vyeevani/a52a03f5c960d409f9107b8ac8ec709f

I have tried your code. It does help a lot! Do you have some idea how to organize these trajs based on the 13 skills as mentioned in the paper?

**Comment by vyeevani** [comment]
You should just be able to iterate through all of the examples in the torch dataset, put samples into a dictionary using the lang_txt field.

**Comment by Lucca-cherries** [comment]
> You should just be able to iterate through all of the examples in the torch dataset, put samples into a dictionary using the lang_txt field.

It should make sense. However, the lang.txt is too low-level. For example, it includes many details about the object, the direction etc. For one Pick and Place skill, there are various corresponding language descriptions. How can I group them in one folder, say 'pick_and_place'? I know some folder names contain 'pnp' which should stands for this, but not all the pnp trajs are inside folders with 'pnp'. Moreover, some 'pnp' folders include other skills.

**Comment by HomerW** [comment]
Hi @Lucca-cherries, unfortunately we don't have a good way of filtering out specific skills since many skills are mixed together in a lot of the data. However, we used this code to create Figure 3 in the paper. Given a path in the data, it categorizes the data into potentially multiple skill categories. If you want data that only contains the pick-and-place skill, you could select the paths for which this function returns just `frozenset("pnp")`.

```
def skill_fn(path):
    l = set()
    if any(x in path for x in ["put", "pick", "take", "pnp", "icra", "rss", "many_skills", "lift_bowl", "move_drying", "wipe", "right_pepper", "topple", "upright", "flip"]):
        l.add("pnp")
    if any(x in path for x in ["fold_"]):
        l.add("fold")
    if any(x in path for x in ["stack_blocks"]):
        l.add("stack")
    if any(x in path for x in ["sweep_granular"]):
        l.add("sweep_granular")
    if any(x in path for x in ["turn_faucet", "turn_lever", "lever_vertical", "move_faucet", "twist_knob", "move_light", "zip", "drawer_pnp", "open", "close_"]):
        l.add("manip")
    if any(x in path for x in ["pour", "end_effector"]):
        l.add("other")
    return frozenset(l)
```

**Comment by Stardust-hyx** [comment]
Pytorch BC/RL Implementations for BridgeData is now available!
See https://github.com/Stardust-hyx/Bridge-Torch
Since most open-source LLMs are implemented with Pytorch and require memory-efficient distributed training frameworks (e.g. Deepspeed) to fine-tune on, we believe our repository can greatly facilitate the application of Multimodal LLMs on this field.

We provide implementations for the following methods:

Goal-conditioned BC
Goal-condtioned IQL (TODO)

An checkpoint for GCBC as well as a torch-version of eval.py are also provided in the repository. We will be grateful if someone can help check the validity of the checkpoint by trying it out.

By the way, a novel generative VLM-based BC method is under development by us. Stay tuned.
